### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by letientai299** [letientai299/userscript-auto-toc#1]
TODO
=====

Doc
---

- [x] Write proper Readme.
- [x] Document source code.
- [x] Demo

Bugs
----

- [x] TOC show on all `body` tags, include one under `iframe`
- [ ] TOC show also the hidden elements, when use with Stylish custom style.
- [ ] Only resizable on Github
- [ ] Auto highlighted header is not works correctly.
- [ ] CSS is override by other plugins/scripts.
- [ ] Shortcut doesn't work if the page is not focused.
- [ ] TOC overlap with contents
- [ ] TOC not updated when open other article within the current page.
- [ ] Header style is affected by site css.

Spread the world
---------

- [ ] Make a github.io page for this.
- [x] Share to friends for beta-testing
- [ ] Publish on OpenUserJS, Userscript...

Enhancements
------------

- [x] Auto upgrade from user side.
- [ ] Enable sites list should be configurable.
- [ ] Should have configurable shortcuts
- [ ] Icons, animations.
- [ ] Better Article detection
- [ ] Expand, Close animation
- [ ] More shortcut keys: Zooms, Search, Next, Back, Expand, Close
- [ ] Configurable css
- [ ] More default style
- [ ] Settings
- [ ] Make it an standalone addon, not depend on any script engine.
- [x] Test on other user script engines.
- [x] Test on other browser.
- [ ] Resizable
- [ ] Movable (floating mode)
- [ ] Left/Right
- [ ] TOC search
- [ ] Should remember the last status (show/hide, width) for a specific site.

Dev
---

- [ ] Unit test
- [ ] Dev setup: auto reload, shorter edit-run circle
- [ ] npm setup
- [ ] Separate js, css, html. Make grunt/gulp tasks to combine everything in one bundle.

Integration
-----------

- [ ] Integrate with VimFx mark and `g[`, `g]` features.
- [ ] Integrate with AsciiDoc preview addon.
- [ ] Sync settings with Firefox/Google profiles
